//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class ad
    {
        public ad()
        {
            this.reports = new HashSet<report>();
        }
    
        public int ad_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public int area_id { get; set; }
        public string catagory { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int cityId { get; set; }
        public System.DateTime date { get; set; }
        public string name { get; set; }
        public string e_mail { get; set; }
        public string phone { get; set; }
        public string url1 { get; set; }
        public byte[] url2 { get; set; }
        public string url3 { get; set; }
        public decimal price { get; set; }
        public string type { get; set; }
        public Nullable<int> view { get; set; }


        [Required(ErrorMessage = "Please browse your image")]
        [Display(Name = "Upload Image")]

        [ValidateFile1]
        public HttpPostedFileBase Photo { get; set; }


        [Required(ErrorMessage = "Please browse your image")]
        [Display(Name = "Upload Image")]

        [ValidateFile1]
        public HttpPostedFileBase Photo1 { get; set; }






        public virtual area area { get; set; }
        public virtual city city { get; set; }
        public virtual user user { get; set; }
        public virtual view view1 { get; set; }
        public virtual ICollection<report> reports { get; set; }
    }
}
