//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public city()
        {
            this.ads = new HashSet<ad>();
        }
    
        public int cityId { get; set; }
        public string cityName { get; set; }
        public int area_id { get; set; }
    
        public virtual ICollection<ad> ads { get; set; }
        public virtual area area { get; set; }
    }
}
