//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BSEntities8 : DbContext
    {
        public BSEntities8()
            : base("name=BSEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ad> ads { get; set; }
        public DbSet<area> areas { get; set; }
        public DbSet<city> cities { get; set; }
        public DbSet<Iuser> Iusers { get; set; }
        public DbSet<report> reports { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<view> views { get; set; }
        public DbSet<Photo> Photos { get; set; }
    }
}
