//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class Photo
    {
        public int Id { get; set; }
        public string path { get; set; }



        [Required(ErrorMessage = "Please browse your image")]
        [Display(Name = "Upload Image")]

        [ValidateFile1]
        public HttpPostedFileBase photo { get; set; }








        public string name { get; set; }
    }
}
