//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.ads = new HashSet<ad>();
            this.Iusers = new HashSet<Iuser>();
        }
    
        public int user_id { get; set; }
        public string name { get; set; }
        public string e_mail { get; set; }
        public string password { get; set; }
        public Nullable<bool> enable { get; set; }
        public string cpass { get; set; }
    
        public virtual ICollection<ad> ads { get; set; }
        public virtual ICollection<Iuser> Iusers { get; set; }
    }
}
